name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: user
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fwerkor
          template: classic
          config_display: large

          plugin_rss: true
          plugin_rss_source: https://blog.fwerkor.com/feed
          plugin_rss_limit: 4

          plugin_isocalendar: true

          plugin_reactions: true

          plugin_stargazers: true

          plugin_pagespeed: true
          plugin_pagespeed_url: "https://blog.fwerkor.com"
          plugin_pagespeed_detailed: true
          plugin_pagespeed_screenshot: true
